version: "3"
services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-config1:/etc/postgresql
      - postgres-data1:/var/lib/postgresql/data
      - postgres-logs1:/var/log/postgresql
      - ./database-backup:/database-backup
  django:
    build: .
    command: python /var/www/backend/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/var/www/backend
    ports:
     - "81:8001"
    depends_on:
     - db
volumes:
  postgres-config1:
  postgres-data1:
  postgres-logs1:
