version: "3"
services:
  student_db:
    restart: always
    image: postgres
    volumes:
      - postgres-config1:/etc/postgresql
      - postgres-data1:/var/lib/postgresql/data
      - postgres-logs1:/var/log/postgresql
      - ./database-backup:/database-backup
  student_django:
    build: .
    command: python /var/www/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/backend
    ports:
     - "80:8000"
    depends_on:
     - student_db
volumes:
  postgres-config1:
  postgres-data1:
  postgres-logs1: