# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171208_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='students_maxedOut',
            field=models.BooleanField(default=False),
        ),
    ]
