# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mentor_students_maxedout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='students_maxedOut',
            new_name='students_maxedout',
        ),
    ]
