# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171208_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='field_of_study',
            new_name='fieldOfStudy',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='research_interest',
            new_name='researchInterest',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='students_maxedout',
            new_name='studentsMaxedOut',
        ),
    ]
