# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171208_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='fieldOfStudy',
            new_name='fieldofstudy',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='researchInterest',
            new_name='researchinterest',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='studentsMaxedOut',
            new_name='studentsmaxedOut',
        ),
    ]
