# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 00:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171208_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentorsclicked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=None),
        ),
    ]
