# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171211_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentorsmaxedout',
            field=models.BooleanField(default=False),
        ),
    ]
