# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_student_mentorsmaxedout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mentorsmaxedout',
        ),
        migrations.AddField(
            model_name='student',
            name='noofmentors',
            field=models.IntegerField(default=0),
        ),
    ]
