# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171211_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='studentsmaxedOut',
            new_name='studentsmaxedout',
        ),
    ]
